### ISSUE TITLE
Any reason for root-namespaced php built-in functions?

### ISSUE THREAD

**Issue by adriansuter** [slimphp/Slim-Psr7#49]
In `\Slim\Psr7\NonBufferedBody::write()` there are four function calls to php built-in functions. All of them are root-namespaced.

- `ob_get_level`
- `ob_get_clean`
- `flush`
- `strlen`

Is there any reason for that?

https://github.com/slimphp/Slim-Psr7/blob/636bea03e39c581b294f7cc5fd27fc910df83f29/src/NonBufferedBody.php#L99-L107

**Comment by l0gicgate** [comment]
There isn't. This was just code ported from Slim 3. I missed it during the code review. You can PR that if you want!

**Comment by JoeBengalen** [comment]
FYI; Using the root-namespaced function calls is a micro performance optimization.
Why and how this works is explained by nikic in this video: https://youtu.be/M8Ktic5sPlo?t=2158

In short it is because PHP compiler will optimize internal functions call. Problem with non root namespaced function calls is that the compiler does not know if it is calling a root function or a function within the current namespace, because the compiler only parses a single file at a time.

**Comment by l0gicgate** [comment]
@JoeBengalen I'd like to add more tests to the `NonBufferedBody` functionality later one. We will need to stub these functions so we can't use root namespace functions.

**Comment by JoeBengalen** [comment]
Oki, if it is required sure. Just wanted you to be aware of it :)

**Comment by danopz** [comment]
Is it really worth it to drop performance improvements for kind of "better" unit tests?

**Comment by l0gicgate** [comment]
@danopz I'd much rather have test coverage than a micro-optimization that really doesn't make a difference on the grand scheme of things.
