### ISSUE TITLE
Test case: Override of php built-in function or real file

### ISSUE THREAD

**Issue by adriansuter** [slimphp/Slim-Psr7#61]
To be able to test the following case, should we override the function `is_readable()`? Or do you prefer a real non-readable file?

https://github.com/slimphp/Slim-Psr7/blob/master/src/Factory/UploadedFileFactory.php#L33

If override, where do you want to have the file for overrides in the `Slim\Psr7\Factory` namespace?

**Comment by l0gicgate** [comment]
Yes, that's the only way to do it. I'd like to change the way we include the overrides. We should add them via the `bootstrap.php` instead of `composer.json`.

**Comment by adriansuter** [comment]
Okay. So I will add the file with the namespaced overrides into `tests/Assets`. And then in `bootstrap.php` I will include the file. Is that the way to go?

**Comment by l0gicgate** [comment]
Yes I think that's the better way to go since it's more explicit that those files are included before the test suite runs. 

For example looking at https://github.com/slimphp/Slim/issues/2669 his build for Fedora RPMs failed because the bootstrapping wasn't being done for those overrides because they don't use composer.

So yes. Add the overrides into `tests/Assets` and require them inside `bootstrap.php`. We should do the same on Slim 3 and Slim 4 as well.
